apiVersion: apps/v1
kind: Deployment
metadata:
  name: orange
  namespace: trouble
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orange
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orange
    spec:
      containers:
      - command:
        - sh
        - -c
        - sleep infinity
        image: alpine
        imagePullPolicy: Always
        name: orange
 

