apiVersion: apps/v1
kind: Deployment
metadata:
  name: danny-app
  labels:
    task: deploy
    app: danny-app
    student: danny
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: danny-app
  template:
    metadata:
      labels:
        deploy: danny-app
        kind: redis
        role: master
        tier: db
    spec:
      containers:
      - image: redis:5-alpine
        name: redis-master
        ports:
        - containerPort: 6379
      initContainers:
      - name: init
        image: busybox:1.34
        command:
        - sh
        - -c
        args:
        - sleep 10
  