apiVersion: v1
kind: Service
metadata:
  name: random-generator2
  labels:
    app: random-generator2
spec:
  clusterIP: None
  selector:
    app: random-generator2
  ports:
  - port: 81
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: random-generator2
  labels:
    app: random-generator2
spec:
  selector:
    matchLabels:
      app: random-generator2
  serviceName: random-generator2
  replicas: 3
  template:
    metadata:
      labels:
        app: random-generator2
    spec:
      containers:
      - name: random-generator2
        image: sbeliakou/random-generator:1
        ports:
        - containerPort: 80