apiVersion: v1
kind: Pod
metadata:
  name: envtest
spec:
  containers:
  - name: envtest
    image: busybox:1.34
    command:
      - sh
      - -c
    args:
      - env && sleep infinity
    env:
      - name: STUDENT_FIRST_NAME 
        value: Danny
      - name: STUDENT_LAST_NAME
        value: Herrera
  
  