apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis-db
  name: redis-db
  namespace: trouble
spec:
  containers:
  - name: redis-db
    command:
    - sh
    - -c
    args:
    - sleep infinity
    image: busybox
    
  
  